# Generated by Django 5.2.8 on 2025-12-19 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainer_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainerprofile",
            name="is_verified",
        ),
    ]
