# Generated by Django 5.2.8 on 2025-12-08 15:00

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_id",
                    models.UUIDField(
                        db_index=True, help_text="UUID from auth_service User"
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "calories_intake",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "protein_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "carbs_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "fats_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "calories_burned",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "steps",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "sleep_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(24),
                        ],
                    ),
                ),
                ("photo_urls", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "daily_metrics",
                "indexes": [
                    models.Index(
                        fields=["user_id", "date"],
                        name="daily_metri_user_id_87e766_idx",
                    ),
                    models.Index(fields=["date"], name="daily_metri_date_07dd2d_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "date"), name="unique_user_date"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="UUID from auth_service User",
                        unique=True,
                    ),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(500),
                        ],
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("maintenance", "Maintenance"),
                            ("bulking", "Bulking"),
                            ("cutting", "Cutting / Fat loss"),
                            ("recomposition", "Body Recomposition"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "body_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ectomorph", "Ectomorph"),
                            ("mesomorph", "Mesomorph"),
                            ("endomorph", "Endomorph"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "activity_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sedentary", "Sedentary"),
                            ("light", "Lightly active"),
                            ("moderate", "Moderately active"),
                            ("active", "Active"),
                            ("very_active", "Very active"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "exercise_experience",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=32,
                    ),
                ),
                ("diet_constraints", models.JSONField(blank=True, default=dict)),
                ("allergies", models.JSONField(blank=True, default=list)),
                ("medical_conditions", models.JSONField(blank=True, default=list)),
                ("supplements", models.JSONField(blank=True, default=list)),
                ("preferred_equipment", models.JSONField(blank=True, default=list)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("language", models.CharField(default="en", max_length=16)),
                ("notes", models.TextField(blank=True)),
                ("is_premium", models.BooleanField(default=False)),
                ("profile_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_profile",
                "indexes": [
                    models.Index(
                        fields=["user_id"], name="user_profil_user_id_4f95f8_idx"
                    ),
                    models.Index(fields=["goal"], name="user_profil_goal_4c8791_idx"),
                    models.Index(
                        fields=["is_premium"], name="user_profil_is_prem_38b13f_idx"
                    ),
                ],
            },
        ),
    ]
