# Generated by Django 5.2.8 on 2025-12-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_id",
            field=models.UUIDField(
                help_text="UUID from auth_service User", unique=True
            ),
        ),
    ]
