# Generated by Django 5.2.8 on 2025-12-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0002_alter_userprofile_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="language",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="timezone",
        ),
    ]
