# Generated by Django 5.2.8 on 2025-12-20 12:41

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0003_remove_userprofile_language_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainerBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(unique=True)),
                ("trainer_user_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["trainer_user_id"],
                        name="user_app_tr_trainer_77f525_idx",
                    ),
                    models.Index(
                        fields=["user_id"], name="user_app_tr_user_id_f37a2e_idx"
                    ),
                ],
            },
        ),
    ]
