# Generated by Django 5.2.8 on 2025-12-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0004_trainerbooking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainerbooking",
            name="user_id",
            field=models.UUIDField(),
        ),
    ]
