# Generated by Django 5.2.8 on 2025-12-22 06:35

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0005_alter_trainerbooking_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DietPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("daily_calories", models.IntegerField()),
                ("macros", models.JSONField()),
                ("meals", models.JSONField()),
                ("version", models.CharField(default="diet_v1", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FoodLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("date", models.DateField()),
                (
                    "source",
                    models.CharField(
                        choices=[("plan", "Followed Plan"), ("custom", "Custom Meal")],
                        max_length=10,
                    ),
                ),
                ("items", models.JSONField()),
                ("calories", models.IntegerField()),
                ("protein", models.IntegerField()),
                ("carbs", models.IntegerField()),
                ("fat", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="DailyMetrics",
        ),
        migrations.AddIndex(
            model_name="dietplan",
            index=models.Index(
                fields=["user_id"], name="user_app_di_user_id_b77b8b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="foodlog",
            unique_together={("user_id", "date")},
        ),
    ]
