# Generated by Django 5.2.8 on 2025-12-22 15:28

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0006_dietplan_foodlog_delete_dailymetrics_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("date", models.DateField()),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("plan", "AI Plan"),
                            ("custom", "Custom"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=10,
                    ),
                ),
                ("items", models.JSONField(blank=True, null=True)),
                ("calories", models.IntegerField(default=0)),
                ("protein", models.IntegerField(default=0)),
                ("carbs", models.IntegerField(default=0)),
                ("fat", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="WeightLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("weight_kg", models.FloatField()),
                ("logged_at", models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name="FoodLog",
        ),
        migrations.AddIndex(
            model_name="meallog",
            index=models.Index(
                fields=["user_id", "date"], name="user_app_me_user_id_2ebd71_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="meallog",
            unique_together={("user_id", "date", "meal_type")},
        ),
    ]
