# Generated by Django 5.2.8 on 2025-12-23 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0007_meallog_weightlog_delete_foodlog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="target_weight_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(500),
                ],
            ),
        ),
    ]
