# Generated by Django 5.2.8 on 2025-12-23 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0008_userprofile_target_weight_kg"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietplan",
            name="week_start",
            field=models.DateField(default=datetime.date(2025, 12, 22)),
            preserve_default=False,
        ),
    ]
