# Generated by Django 5.2.8 on 2025-12-26 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0009_dietplan_week_start"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="dietplan",
            name="user_app_di_user_id_b77b8b_idx",
        ),
        migrations.AlterUniqueTogether(
            name="meallog",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="dietplan",
            name="week_end",
            field=models.DateField(default=datetime.date(2025, 12, 26)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meallog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 12, 26, 8, 37, 17, 187118, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="meallog",
            name="carbs",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="meallog",
            name="fat",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="meallog",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("breakfast", "Breakfast"),
                    ("lunch", "Lunch"),
                    ("dinner", "Dinner"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="meallog",
            name="protein",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="meallog",
            name="source",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("custom", "Custom"),
                    ("extra", "Extra"),
                    ("skipped", "Skipped"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="meallog",
            index=models.Index(
                fields=["user_id", "date", "meal_type"],
                name="user_app_me_user_id_c43172_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="weightlog",
            index=models.Index(
                fields=["user_id", "logged_at"], name="user_app_we_user_id_de7af5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dietplan",
            constraint=models.UniqueConstraint(
                fields=("user_id", "week_start"), name="unique_user_week_plan"
            ),
        ),
    ]
