# Generated by Django 5.2.8 on 2025-12-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0010_remove_dietplan_user_app_di_user_id_b77b8b_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="meallog",
            name="user_app_me_user_id_c43172_idx",
        ),
        migrations.AddConstraint(
            model_name="meallog",
            constraint=models.UniqueConstraint(
                fields=("user_id", "date", "meal_type"), name="unique_meal_per_day"
            ),
        ),
    ]
