# Generated by Django 5.2.8 on 2025-12-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0011_remove_meallog_user_app_me_user_id_c43172_idx_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="meallog",
            name="unique_meal_per_day",
        ),
        migrations.RemoveIndex(
            model_name="meallog",
            name="user_app_me_user_id_2ebd71_idx",
        ),
        migrations.AlterField(
            model_name="meallog",
            name="calories",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="meallog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="meallog",
            name="source",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("custom", "Custom"),
                    ("skipped", "Skipped"),
                    ("extra", "Extra"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="meallog",
            constraint=models.UniqueConstraint(
                fields=("user_id", "date", "meal_type"),
                name="unique_meal_per_user_per_day",
            ),
        ),
    ]
