# Generated by Django 5.2.8 on 2025-12-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0012_remove_meallog_unique_meal_per_day_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="meallog",
            name="unique_meal_per_user_per_day",
        ),
        migrations.AddConstraint(
            model_name="meallog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("meal_type", "other"), _negated=True),
                fields=("user_id", "date", "meal_type"),
                name="unique_main_meal_per_user_per_day",
            ),
        ),
    ]
