# Generated by Django 5.2.8 on 2025-12-27 13:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0013_remove_meallog_unique_meal_per_user_per_day_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True)),
                ("date", models.DateField(db_index=True)),
                ("exercise_name", models.CharField(max_length=128)),
                ("duration_sec", models.PositiveIntegerField(default=0)),
                ("calories_burnt", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("completed", "Completed"), ("skipped", "Skipped")],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "workout_log",
                "unique_together": {("user_id", "date", "exercise_name")},
            },
        ),
        migrations.CreateModel(
            name="WorkoutPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True)),
                ("week_start", models.DateField(db_index=True)),
                ("week_end", models.DateField(db_index=True)),
                ("goal", models.CharField(max_length=32)),
                (
                    "workout_type",
                    models.CharField(
                        choices=[
                            ("cardio", "Cardio"),
                            ("strength", "Strength"),
                            ("mixed", "Mixed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("sessions", models.JSONField()),
                ("estimated_weekly_calories", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "workout_plan",
                "unique_together": {("user_id", "week_start")},
            },
        ),
    ]
