# Generated by Django 5.2.8 on 2026-01-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0014_workoutlog_workoutplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="dietplan",
            name="daily_calories",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dietplan",
            name="macros",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dietplan",
            name="meals",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
