# Generated by Django 5.2.8 on 2026-01-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0015_dietplan_status_alter_dietplan_daily_calories_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PremiumPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("price", models.PositiveIntegerField(help_text="Price in INR")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "premium_plan",
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="premium_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
