# Generated by Django 5.2.8 on 2026-01-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0016_premiumplan_userprofile_premium_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
