# Generated by Django 5.2.8 on 2026-01-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
