# Generated by Django 5.2.8 on 2026-01-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chatroom_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="last_message_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="file_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="mime_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="message",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="sender_role",
            field=models.CharField(
                choices=[("user", "User"), ("trainer", "Trainer")],
                default="user",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["room", "created_at"], name="chat_messag_room_id_5feac5_idx"
            ),
        ),
    ]
