# Generated by Django 5.2.8 on 2025-12-09 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshTokenRecord",
            fields=[
                (
                    "jti",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("revoked", models.BooleanField(db_index=True, default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["expires_at"], name="auth_app_re_expires_dd3a93_idx"
                    ),
                    models.Index(
                        fields=["revoked"], name="auth_app_re_revoked_dde5f5_idx"
                    ),
                ],
            },
        ),
    ]
