# Generated by Django 5.2.8 on 2025-12-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0002_refreshtokenrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
    ]
